name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print API_KEY
        shell: bash
        run: |
          echo "The API key is: ${{ secrets.API_KEY }}"
